- name: Setting present kernel params
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    ignoreerrors: yes
    state: present
    reload: yes
  with_items:
    - { name: 'vm.max_map_count', value: 655360 }
    - { name: 'fs.file-max', value: 6553600 }
    - { name: 'vm.swappiness', value: 0 }
    - { name: 'kernel.sysrq', value: 1 }
    - { name: 'net.ipv4.neigh.default.gc_stale_time', value: 120 }
    - { name: 'net.ipv4.tcp_max_tw_buckets', value: 5000 }
    - { name: 'net.ipv4.tcp_syncookies', value: 1 }
    - { name: 'net.ipv4.tcp_max_syn_backlog', value: 1024 }
    - { name: 'net.ipv4.tcp_synack_retries', value: 2 }
    - { name: 'net.ipv4.ip_forward', value: 1 }

- name: Update /etc/security/limits.conf
  blockinfile:
    dest: /etc/security/limits.conf
    insertbefore: '# End of file'
    block: |
      *       soft    nproc   131072
      *       hard    nproc   131072
      *       soft    nofile  131072
      *       hard    nofile  131072
      root    soft    nproc   131072
      root    hard    nproc   131072
      root    soft    nofile  131072
      root    hard    nofile  131072
